# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Cache docker stage images
      uses: actions/cache@v1
      with:
        path: /var/lib/docker/overlay2
        key: ${{ runner.os }}-docker-staged-builds
    
    - name: Build and Push to Humanitec
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: awesome-company
