name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout git repo
      uses: actions/checkout@v2
      
    - run: docker info

    - name: Cache docker stage images
      uses: actions/cache@v1
      with:
        path: /var/lib/docker/overlay2
        key: ${{ runner.os }}-docker-staged-builds
    
    - name: Build and Push to Humanitec
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: chris-test-org
